# This file is part of Supysonic.
# Supysonic is a Python implementation of the Subsonic server API.
#
# Distributed under terms of the GNU AGPLv3 license.

"""The ffmpeg passes against a REAL ffmpeg, on signals whose answer is known.

Everything else in the suite tests the code around ffmpeg with stderr written
by hand. That is the right way to pin the parsing and the error paths, and the
wrong way to know whether the command lines still mean what the parsers
assume: a filter renamed, a line format changed, an option applied at a
different point of the graph — none of it shows up against a transcript. It
showed up here the first time this ran: current ffmpeg closes a trailing
silence when it flushes at EOF, and the trailing trim had been reading only
the older "open" form, so it never trimmed anything.

The material is generated by ffmpeg itself (lavfi), so there is no fixture to
keep, and every expected number is physics rather than a snapshot: a full-scale
sine is -3.01 LUFS, white noise is spectrally flat, a kick every 60/128 s is
128 BPM. Measured values are written next to each assertion.

Skipped without ffmpeg — except where the environment says it must be there
(``NS_REQUIRE_FFMPEG=1``, set by the CI job that installs it): a skip there
would be the suite quietly testing less than it claims.
"""

import math
import os
import shutil
import subprocess
import tempfile
import unittest

HAVE_FFMPEG = shutil.which("ffmpeg") is not None

if not HAVE_FFMPEG and os.environ.get("NS_REQUIRE_FFMPEG") == "1":  # pragma: no cover
    raise RuntimeError("NS_REQUIRE_FFMPEG=1 but ffmpeg is not on PATH")


def _render(path, *graph_args):
    subprocess.run(
        ["ffmpeg", "-v", "error", "-nostdin", "-y", *graph_args, "-c:a", "flac", path],
        check=True,
        timeout=60,
    )


def _kick(bpm, seconds=40):
    """A pitched kick on every beat: a sine swept 205 -> 45 Hz, decaying.

    The way a kick is actually made (a pitch envelope on a sine), which is
    also why it is the case the envelope tracker exists for.
    """
    p = 60.0 / bpm
    expr = (
        f"0.8*sin(2*PI*(45+160*exp(-35*mod(t\\,{p})))*mod(t\\,{p}))"
        f"*exp(-9*mod(t\\,{p}))"
    )
    return ["-f", "lavfi", "-i", f"aevalsrc='{expr}':s=44100:d={seconds}"]


@unittest.skipUnless(HAVE_FFMPEG, "needs ffmpeg")
class FfmpegTestCase(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.dir = tempfile.mkdtemp()
        cls.files = {}

    @classmethod
    def tearDownClass(cls):
        shutil.rmtree(cls.dir, ignore_errors=True)

    @classmethod
    def file(cls, name, *graph_args):
        if name not in cls.files:
            path = os.path.join(cls.dir, name + ".flac")
            _render(path, *graph_args)
            cls.files[name] = path
        return cls.files[name]


class SpectralPassTestCase(FfmpegTestCase):
    def test_a_sine_is_tonal_and_where_it_should_be(self):
        from supysonic.deezer.analysis import _spectral

        # lavfi's sine is 1/8 of full scale; volume 0.1 more: 0.0125 peak.
        f = _spectral(self.file(
            "sine", "-f", "lavfi", "-i",
            "sine=frequency=1000:sample_rate=44100:duration=20,volume=0.1",
        ))
        # Measured 1012.6 Hz: a 2048-point window's leakage around the bin.
        self.assertAlmostEqual(f["centroid"], 1000, delta=40)
        # Measured 0.022: a pure tone is as un-flat as a spectrum gets.
        self.assertLess(f["flatness"], 0.1)
        # BS.1770: a full-scale 1 kHz sine is -3.01 LUFS, so this one is
        # -3.01 + 20*log10(0.0125) = -41.07. Measured -41.1.
        self.assertAlmostEqual(f["lufs"], -3.01 + 20 * math.log10(0.0125), delta=0.3)
        # A steady tone has no loudness range at all. Measured 0.0.
        self.assertLess(f["lra"], 0.5)
        self.assertGreater(f["frames"], 500)

    def test_white_noise_is_flat_and_bright(self):
        from supysonic.deezer.analysis import _spectral

        f = _spectral(self.file(
            "noise", "-f", "lavfi", "-i",
            "anoisesrc=color=white:amplitude=0.3:duration=20:sample_rate=44100:seed=7",
        ))
        # Measured 0.846 (a sine: 0.022).
        self.assertGreater(f["flatness"], 0.7)
        # Measured 11 kHz: half the SOURCE rate's Nyquist — the stats see the
        # 44.1 kHz input, not the 22 kHz output (see _spectral_cmd).
        self.assertGreater(f["centroid"], 5000)
        self.assertGreater(f["rolloff"], f["centroid"])

    def test_a_few_noisy_frames_do_not_make_a_tone_flat(self):
        """The descriptors describe the TYPICAL frame (a median), not the worst."""
        from supysonic.deezer.analysis import _spectral

        # A tone with a 0.15 s burst of noise every 2 s: 7.5% of the frames.
        f = _spectral(self.file(
            "tone_bursts", "-filter_complex",
            "sine=frequency=1000:sample_rate=44100:duration=20,volume=4[s];"
            "anoisesrc=color=white:amplitude=0.5:sample_rate=44100:duration=20:seed=4,"
            "volume='between(mod(t\\,2)\\,0\\,0.15)':eval=frame[n];"
            "[s][n]amix=inputs=2:normalize=0",
        ))
        # Measured: median 0.0018 — the burst frames reach 0.82.
        self.assertLess(f["flatness"], 0.1)

    def test_the_loudness_range_tells_squashed_from_dynamic(self):
        """LRA is the classifier's "how limitered is this" axis."""
        from supysonic.deezer.analysis import _spectral

        steady = _spectral(self.file("kick128", *_kick(128)))
        dynamic = _spectral(self.file(
            "dynamic", "-filter_complex",
            "anoisesrc=color=pink:amplitude=0.05:duration=12:sample_rate=44100:seed=1[a];"
            "anoisesrc=color=pink:amplitude=0.5:duration=12:sample_rate=44100:seed=2[b];"
            "[a][b]concat=n=2:v=0:a=1",
        ))
        # Measured 0.6 LU for the kick loop and 20.1 LU for a 20 dB step.
        self.assertLess(steady["lra"], 3)
        self.assertGreater(dynamic["lra"], 15)

    def test_an_undecodable_file_says_why(self):
        from supysonic.deezer.analysis import _spectral

        bogus = os.path.join(self.dir, "bogus.flac")
        with open(bogus, "wb") as fh:
            fh.write(b"fLaC" + os.urandom(4096))
        with self.assertRaises(Exception) as ctx:
            _spectral(bogus)
        # ffmpeg's own words, not "ffmpeg exited 1".
        self.assertNotEqual(str(ctx.exception).strip(), "")
        self.assertNotIn("ffmpeg version", str(ctx.exception))


class TempoTestCase(FfmpegTestCase):
    def test_kicks_read_at_their_tempo(self):
        from supysonic.deezer.analysis import _measure_tempo

        # 174 is the trap case: 34.5 slots of the 100 Hz grid per beat, so a
        # tracker that only tries whole lags reads it as its own half or double.
        for bpm in (90, 128, 174):
            with self.subTest(bpm=bpm):
                measured, conf, _grid = _measure_tempo(self.file(f"kick{bpm}", *_kick(bpm)))
                # Measured exactly 90.0 / 128.0 / 174.0, confidence 0.52 / 0.62 / 0.30.
                self.assertAlmostEqual(measured, bpm, delta=1.0)
                self.assertGreater(conf, 0.2)

    def test_an_offbeat_stab_does_not_double_the_tempo(self):
        """What the 170 Hz low-pass is for (hard house's offbeat "donk").

        Hi-hats never reach the envelope anyway — the resample to 1 kHz
        removes everything above 500 Hz — so the band the low-pass guards is
        170-500 Hz, which is exactly where an offbeat bass stab sits.
        """
        from supysonic.deezer.analysis import _measure_tempo

        p = 60.0 / 128
        kick = (
            f"0.5*sin(2*PI*(45+160*exp(-35*mod(t\\,{p})))*mod(t\\,{p}))"
            f"*exp(-9*mod(t\\,{p}))"
        )
        donk = f"0.5*sin(2*PI*300*t)*exp(-25*mod(t+{p / 2}\\,{p}))"
        bpm, _conf, _grid = _measure_tempo(self.file(
            "donk", "-f", "lavfi", "-i", f"aevalsrc='{kick}+{donk}':s=44100:d=40",
        ))
        # Measured 128.0; without the low-pass the stab reads 256.0.
        self.assertAlmostEqual(bpm, 128, delta=1.0)

    def test_kicks_over_a_held_bass_keep_their_tempo(self):
        from supysonic.deezer.analysis import _measure_tempo

        p = 60.0 / 128
        kick = (
            f"0.6*sin(2*PI*(45+160*exp(-35*mod(t\\,{p})))*mod(t\\,{p}))"
            f"*exp(-9*mod(t\\,{p}))"
        )
        path = self.file(
            "kick_bass", "-f", "lavfi", "-i",
            f"aevalsrc='{kick}+0.3*sin(2*PI*55*t)':s=44100:d=40",
        )
        bpm, conf, _grid = _measure_tempo(path)
        # Measured 128.0 at 0.53. (At 174 BPM the same bass pulls it to 171:
        # see the known fault below.)
        self.assertAlmostEqual(bpm, 128, delta=1.0)

    @unittest.expectedFailure
    def test_a_held_note_has_no_tempo(self):
        """KNOWN FAULT, stated rather than papered over.

        The envelope _low_envelope builds is the PEAK of each 10 ms block of a
        signal low-passed at 170 Hz. A steady note whose period does not fit
        the block grid gives a block peak that ripples with the phase, and the
        positive steps of that ripple read as an onset train. Measured on pure
        30 s tones: 40 Hz -> 200 BPM (conf 0.48), 55 Hz -> 300 (0.53),
        82 Hz -> 240 (0.79), 147 Hz -> 60 (0.67), 220 Hz -> 200 (0.49), and a
        pad of detuned saws -> 300 (0.36); only 110 Hz reads as no tempo.
        Drum-less music (ambient, drones, pads) is therefore given a confident
        phantom tempo, which the client then takes as its anchor.

        The fix is a real amplitude envelope (rectify, then smooth below the
        lowest bass period) before the decimation — a change to what every
        measurement reads, so an ANALYSIS_VERSION bump validated on real
        music, not an edit made from a test. When it lands this test starts
        passing and unittest reports an "unexpected success": remove the
        decorator then.
        """
        from supysonic.deezer.analysis import _measure_tempo

        for freq in (55, 82, 220):
            with self.subTest(freq=freq):
                bpm, conf, _grid = _measure_tempo(self.file(
                    f"tone{freq}", "-f", "lavfi", "-i",
                    f"sine=frequency={freq}:sample_rate=44100:duration=30",
                ))
                self.assertTrue(bpm is None or conf < 0.1, (bpm, conf))


class SilenceBoundsTestCase(FfmpegTestCase):
    def _bounds(self, path, threshold=-45.0):
        from supysonic.webui import edges

        return edges._edges(*edges._detect(path, threshold))

    def test_leading_and_trailing_silence_are_found(self):
        path = self.file(
            "gapped", "-filter_complex",
            "anullsrc=r=44100:cl=stereo:d=1[a];"
            "sine=f=440:d=3:r=44100,aformat=channel_layouts=stereo[b];"
            "anullsrc=r=44100:cl=stereo:d=0.5[c];"
            "[a][b][c]concat=n=3:v=0:a=1",
        )
        start, end = self._bounds(path)
        # Measured (1.0, 4.0). The trailing half-second is the one ffmpeg
        # closes at EOF; before the fix this read (1.0, 4.49).
        self.assertAlmostEqual(start, 1.0, delta=0.02)
        self.assertAlmostEqual(end, 4.0, delta=0.02)

    def test_a_file_without_silence_is_left_whole(self):
        path = self.file(
            "solid", "-f", "lavfi", "-i", "sine=frequency=440:sample_rate=44100:duration=5",
        )
        start, end = self._bounds(path)
        self.assertEqual(start, 0.0)
        self.assertAlmostEqual(end, 5.0, delta=0.02)

    def test_a_final_hit_after_a_gap_is_not_trimmed(self):
        # Silence in the middle is not a tail: 2 s of tone, 1 s of nothing,
        # then a last 0.5 s of sound that must still be played.
        path = self.file(
            "coda", "-filter_complex",
            "sine=f=440:d=2:r=44100[a];anullsrc=r=44100:cl=mono:d=1[b];"
            "sine=f=660:d=0.5:r=44100[c];[a][b][c]concat=n=3:v=0:a=1",
        )
        start, end = self._bounds(path)
        self.assertEqual(start, 0.0)
        self.assertAlmostEqual(end, 3.5, delta=0.02)


if __name__ == "__main__":
    unittest.main()
