ALTER TABLE artist ADD COLUMN deezer_id VARCHAR(32);
ALTER TABLE album ADD COLUMN deezer_id VARCHAR(32);
ALTER TABLE album ADD COLUMN cover_md5 VARCHAR(64);
ALTER TABLE track ADD COLUMN deezer_id VARCHAR(32);
ALTER TABLE playlist ADD COLUMN deezer_id VARCHAR(32);
